# .kodiak.toml
version = 1

[approve]
auto_approve_usernames = ["dependabot", "renovate"]

[merge]
method = "squash"
automerge_label = ["ğŸš€ merge", "â¬†ï¸ dependencies"]

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" version upgrades.
versions = ["minor", "patch"]
usernames = ["dependabot", "renovate"]

[update]
autoupdate_label = "â™»ï¸ autoupdate"
