name: Examples E2E
on: [push]
jobs:
  e2e:
    env:
      DATABASE_URL: postgresql://postgres:@localhost:5432/trpcdb
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      matrix:
        dir: [
            express-server,
            # next-chat,
            next-prisma-starter,
            next-prisma-starter-websockets,
            next-prisma-todomvc,
            standalone-server,
          ]
        node-start: ['14.x', '16.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: trpcdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.dir }}-${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      - name: Use Node ${{ matrix.node-start }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-start }}

      - run: node -v
      # - run: yarn install --cwd examples/${{ matrix.dir }} --ignore-scripts
      - run: yarn --ignore-engines playwright install-deps

      - name: if exists, run yarn lint
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"lint"'; then yarn lint; fi
      - run: yarn --cwd examples/${{ matrix.dir }} build
      - run: yarn --cwd examples/${{ matrix.dir }} test-start
      - run: yarn --cwd examples/${{ matrix.dir }} test-dev
