name: Examples E2E
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    env:
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      matrix:
        dir:
          [
            express-server,
            .interop/express-server,
            express-minimal,
            .interop/next-prisma-starter,
            .interop/next-minimal-starter-migration,
            .interop/next-prisma-starter-websockets,
            .interop/next-prisma-todomvc,
            next-minimal-starter,
            minimal-react,
            .interop/next-minimal-starter,
            .interop/standalone-server,
            fastify-server,
            .interop/fastify-server,
            cloudflare-workers,
            .interop/cloudflare-workers,
            next-prisma-starter,
            next-prisma-starter-websockets,
            next-prisma-todomvc,
            standalone-server,
          ]
        node-start: ['16.x']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-

      - run: node -v
      - name: Install deps and build (with cache)
        run: pnpm --filter "./examples/${{ matrix.dir }}/**"  --filter "@trpc/*" --filter root install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/examples/${{ matrix.dir }}/.next/cache
          key: ${{ matrix.dir }}-${{ runner.os }}-${{ matrix.node-start }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-start }}
          cache: 'pnpm'

      - run: node -v

      - name: if exists, run build-sqlite, else run build
        run: |
          cat ./examples/${{ matrix.dir }}/package.json | 
          if grep --silent '"build-sqlite"'; 
            then pnpm --filter ./examples/${{ matrix.dir }} build-sqlite; 
            else pnpm --filter ./examples/${{ matrix.dir }} build;
          fi

      - name: if exists, run test-start
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-start
      - name: if exists, run test-dev
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-dev
