name: Examples E2E
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright
      DATABASE_URL: postgresql://postgres:@postgres:5432/trpcdb
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      matrix:
        dir: [
            express-server,
            .interop/express-server,
            express-minimal,
            .interop/next-prisma-starter,
            .interop/next-minimal-starter-migration,
            .interop/next-prisma-starter-websockets,
            .interop/next-prisma-todomvc,
            next-minimal-starter,
            .interop/next-minimal-starter,
            .interop/standalone-server,
            fastify-server,
            .interop/fastify-server,
            cloudflare-workers,
            .interop/cloudflare-workers,
            next-prisma-starter,
            next-prisma-starter-sqlite,
            next-prisma-starter-websockets,
            # next-prisma-todomvc,
            standalone-server,
          ]
        node-start: ['16.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: trpcdb
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-

      - name: Cache Playwright's binary
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-playwright-bin-v1.26.0
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - run: node -v
      - name: Install deps and build (with cache)
        run: pnpm --filter ./examples/${{ matrix.dir }}  --filter "@trpc/*" --filter root install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}${{ matrix.dir }}/.next/cache
          key: ${{ matrix.dir }}-${{ runner.os }}-${{ matrix.node-start }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-start }}
          cache: 'pnpm'

      - run: node -v

      # - name: Wait for postgres
      #   run: |
      #     until pg_isready -h postgres -p 5432 -U postgres; do
      #       sleep 1
      #     done

      - name: if exists, run lint
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present lint

      - name: Wait for postgres
        run: sleep 100

      - name: if exists, run build
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present build
      - name: if exists, run test-start
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-start
      - name: if exists, run test-dev
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-dev
