name: Examples E2E
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    container:
      image: mcr.microsoft.com/playwright:v1.26.0-focal
      options: --user 1001
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright
      DATABASE_URL: postgresql://postgres:@postgres:5432/trpcdb
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      matrix:
        dir: [
            express-server,
            .interop/express-server,
            express-minimal,
            .interop/next-prisma-starter,
            .interop/next-minimal-starter-migration,
            .interop/next-prisma-starter-websockets,
            .interop/next-prisma-todomvc,
            next-minimal-starter,
            .interop/next-minimal-starter,
            .interop/standalone-server,
            fastify-server,
            .interop/fastify-server,
            cloudflare-workers,
            .interop/cloudflare-workers,
            next-prisma-starter,
            next-prisma-starter-sqlite,
            next-prisma-starter-websockets,
            # next-prisma-todomvc,
            standalone-server,
          ]
        node-start: ['16.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: trpcdb
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Cache Playwright's binary
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-playwright-bin-v1
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - run: node -v
      - name: Install deps and build (with cache)
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}${{ matrix.dir }}/.next/cache
          key: ${{ matrix.dir }}-${{ runner.os }}-${{ matrix.node-start }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-start }}

      - run: node -v

      - name: if exists, run lint
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"lint"'; then pnpm lint; fi
      - name: if exists, run build
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"build"'; then pnpm build; fi
      - name: if exists, run test-start
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"test-start"'; then pnpm test-start; fi
      - name: if exists, run test-dev
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"test-dev"'; then pnpm test-dev; fi
