name: Lint
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2

      - uses: actions/setup-node@v3
        with:
        node-start: ['16.x']
          cache: 'pnpm'

      - name: Cache Playwright's binary
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-playwright-bin-v1
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Install deps and build (with cache)
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - run: pnpm manypkg check
