name: autofix.ci # for "security reasons", this has to be named autofix.ai
permissions:
  contents: read
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  autofix:
    name: 'Lint and auto-fix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/setup

      - name: Run ts-prune
        run: pnpm lint-prune

      # <autofixing>
      - run: pnpm turbo lint -- --fix
        if: ${{ failure() || success() }}
      - run: pnpm manypkg fix
        if: ${{ failure() || success() }}
      - run: pnpm format-fix
        if: ${{ failure() || success() }}
      # </autofixing>

      # commit autofixes
      # - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
      #   if: ${{ failure() || success() }}
      #   with:
      #     commit-message: 'chore: apply lint and formatting fixes'
      #     fail-fast: false
