name: Release "@tmp"-tagged packages

on:
  push:
    branches:
      # Replace this with the branch you want to release from ðŸ‘‡
      - 'export-from-main-nuke-core'
    paths:
      - '.github/workflows/release-tmp.yml'
      - 'packages/**'
      - '!packages/**/package.json'
      - '!packages/test/**'

jobs:
  publish:
    timeout-minutes: 10
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Check version
        run: |
          if [[ $(node -p "require('./packages/server/package.json').version.startsWith('10.')") != true ]]; then
            echo "Error: The version in packages/server/package.json must start with '10.'"
            exit 1
          fi
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-trpc-${{ github.head_ref }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-trpc-${{ github.head_ref }}-

      - name: Install deps (with cache)
        run: pnpm --filter "@trpc/*" --filter root install

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm lerna publish --force-publish --canary major --preid "alpha-tmp-$(pnpm --silent current-branch)" --dist-tag tmp --yes
