name: subtree-matrix
on:
  push:
    branches:
      - main
      - subtree-lockfiles
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync-downstream:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path: [
            #
            next-prisma-starter,
            # next-prisma-websockets-starter,
            # next-prisma-todomvc,
            # next-minimal-starter,
            # next-big-router,
          ]

    name: Update downstream ${{ matrix.path }} package

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: |
          echo "link-workspace-packages=false" >> .npmrc

      - name: Install dependencies and create lockfile
        run: |
          rm pnpm-workspace.yaml
          cd ./examples/${{ matrix.path }} && mv ../../pnpm-lock.yaml . && pnpm install --no-frozen-lockfile

      - name: Commit changes
        run: |
          # git config --global user.email "email-here"
          git config --global user.name "trpc-bot"
          git add . && git commit -m "chore: sync lockfile"

      - name: Sync downstream
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'trpc/examples-${{ matrix.path }}'
          path: 'examples/${{ matrix.path }}'
          deploy_key: ${{ secrets.TRPC_DEPLOY_TOKEN }}
          force: true # will force push to the downstream repository
